## source Diego: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 328066530950.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t teste_dotnet_webapi_ecs_codepipeline_aws .
      - docker tag teste_dotnet_webapi_ecs_codepipeline_aws:latest 328066530950.dkr.ecr.sa-east-1.amazonaws.com/teste_dotnet_webapi_ecs_codepipeline_aws:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 328066530950.dkr.ecr.sa-east-1.amazonaws.com/teste_dotnet_webapi_ecs_codepipeline_aws:latest
      - printf '{"ImageURI":"328066530950.dkr.ecr.sa-east-1.amazonaws.com/teste_dotnet_webapi_ecs_codepipeline_aws:latest"}' > imageDetail.json
artifacts:
    files: imageDetail.json